<a href="https://colab.research.google.com/github/FAYASISMAEL/AI-ML-Visualization-Files/blob/main/Seoul%2BDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Question

The air quality data for this segment has been divided into three different csv files.

`info.csv` has the data hour by hour data about the concentration of polutants in the air and the status of the intruments.
`item_info` has the data for items and levels of concetration.
`station_info` has the data for measuring stations.

Read in all the three datasets and then print the first five rows.

You can download the dataset from kaggle website: https://www.kaggle.com/bappekim/air-pollution-in-seoul

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/Measurement_info.csv')
data

Buffered data was truncated after reaching the output size limit.

In [ ]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns', None) # show all columns
print(data)

Buffered data was truncated after reaching the output size limit.

In [ ]:
item = pd.read_csv('/content/Measurement_item_info.csv')
item

,Item code,Item name,Unit of measurement,Good(Blue),Normal(Green),Bad(Yellow),Very bad(Red)
0,1,SO2,ppm,0.02,0.05,0.15,1.0
1,3,NO2,ppm,0.03,0.06,0.20,2.0
2,5,CO,ppm,2.00,9.00,15.00,50.0
3,6,O3,ppm,0.03,0.09,0.15,0.5
4,8,PM10,Mircrogram/m3,30.00,80.00,150.00,600.0
5,9,PM2.5,Mircrogram/m3,15.00,35.00,75.00,500.0

In [ ]:
station = pd.read_csv('/content/Measurement_station_info.csv')
station

,Station code,Station name(district),Address,Latitude,Longitude
0,101,Jongno-gu,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008
1,102,Jung-gu,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676
2,103,Yongsan-gu,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850
3,104,Eunpyeong-gu,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848
4,105,Seodaemun-gu,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679
5,106,Mapo-gu,"10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic o...",37.555580,126.905597
6,107,Seongdong-gu,"18, Ttukseom-ro 3-gil, Seongdong-gu, Seoul, Re...",37.541864,127.049659
7,108,Gwangjin-gu,"571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republi...",37.547180,127.092493
8,109,Dongdaemun-gu,"43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul...",37.575743,127.028885
9,110,Jungnang-gu,"369, Yongmasan-ro, Jungnang-gu, Seoul, Republi...",37.584848,127.094023
10,111,Seongbuk-gu,"70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Repu...",37.606719,127.027279
11,112,Gangbuk-gu,"49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Rep...",37.647930,127.011952
12,113,Dobong-gu,"34, Sirubong-ro 2-gil, Dobong-gu, Seoul, Repub...",37.654192,127.029088
13,114,Nowon-gu,"17, Sanggye-ro 23-gil, Nowon-gu, Seoul, Republ...",37.658774,127.068505
14,115,Yangcheon-gu,"56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Re...",37.525939,126.856603
15,116,Gangseo-gu,"71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Re...",37.544640,126.835151
16,117,Guro-gu,"45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republi...",37.498498,126.889692
17,118,Geumcheon-gu,"20, Geumha-ro 21-gil, Geumcheon-gu, Seoul, Rep...",37.452357,126.908296
18,119,Yeongdeungpo-gu,"11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul,...",37.525007,126.897370
19,120,Dongjak-gu,"6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Repub...",37.480917,126.971481
20,121,Gwanak-gu,"14, Sillimdong-gil, Gwanak-gu, Seoul, Republic...",37.487355,126.927102
21,122,Seocho-gu,"16, Sinbanpo-ro 15-gil, Seocho-gu, Seoul, Repu...",37.504547,126.994458
22,123,Gangnam-gu,"426, Hakdong-ro, Gangnam-gu, Seoul, Republic o...",37.517528,127.047470
23,124,Songpa-gu,"236, Baekjegobun-ro, Songpa-gu, Seoul, Republi...",37.502686,127.092509
24,125,Gangdong-gu,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792

#### Question

Create a new Dataframe whcih has information about the item code and item name

In [ ]:
sub_item = item[['Item code','Item name']]
# print(sub_item.to_string(index=False))
sub_item

   Item code Item name
0          1       SO2
1          3       NO2
2          5        CO
3          6        O3
4          8      PM10
5          9     PM2.5

#### Question

Create a new Dataframe whcih has information about the station code and station name

In [ ]:
sub_station = station[['Station code','Station name(district)']]
# print(sub_station.to_string(index=False))
sub_station

    Station code Station name(district)
0            101              Jongno-gu
1            102                Jung-gu
2            103             Yongsan-gu
3            104           Eunpyeong-gu
4            105           Seodaemun-gu
5            106                Mapo-gu
6            107           Seongdong-gu
7            108            Gwangjin-gu
8            109          Dongdaemun-gu
9            110            Jungnang-gu
10           111            Seongbuk-gu
11           112             Gangbuk-gu
12           113              Dobong-gu
13           114               Nowon-gu
14           115           Yangcheon-gu
15           116             Gangseo-gu
16           117                Guro-gu
17           118           Geumcheon-gu
18           119        Yeongdeungpo-gu
19           120             Dongjak-gu
20           121              Gwanak-gu
21           122              Seocho-gu
22           123             Gangnam-gu
23           124              Songpa-gu
24           125            Gangdong-gu

In [ ]:
data_i = dict(zip(item['Item code'], item['Item name']))
# print(data_i)
data_n = []

for code in data['Item code']:
    data_n.append(data_i.get(code, 'unknown'))

data.insert(len(data.columns), 'Item name', data_n)
data.head()

,Measurement date,Station code,Item code,Average value,Instrument status,Item name
0,2017-01-01 00:00,101,1,0.004,0,SO2
1,2017-01-01 00:00,101,3,0.059,0,NO2
2,2017-01-01 00:00,101,5,1.200,0,CO
3,2017-01-01 00:00,101,6,0.002,0,O3
4,2017-01-01 00:00,101,8,73.000,0,PM10

In [ ]:
import pandas as pd
data = pd.read_csv("Measurement_info.csv")
new = data["Measurement date"].str.split("-",n=1,expand = True)
data["years"] = new[0]
data["Measurement date"]= new[1]
data = data[['years','Measurement date','Station code','Item code','Average value','Instrument status']]
group = data.groupby(['years', 'Item code'])['Average value'].mean()
group

years  Item code
2017   1             0.003205
       3             0.027870
       5             0.517864
       6             0.023104
       8            44.379726
       9            24.565429
2018   1            -0.001097
       3             0.023507
       5             0.494565
       6             0.018097
       8            41.765160
       9            24.132342
2019   1            -0.007751
       3             0.015891
       5             0.515432
       6             0.012498
       8            45.036843
       9            27.634511
Name: Average value, dtype: float64

In [ ]:
group.first()

                   Measurement date  Item code  Average value  \
years Station code
2017  101               01-01 00:00          1          0.004
      102               01-01 00:00          1          0.006
      103               01-01 00:00          1          0.005
      104               01-01 00:00          1          0.005
      105               01-01 00:00          1          0.005
...                             ...        ...            ...
2019  121               01-01 01:00          1          0.005
      122               01-01 01:00          3          0.049
      123               01-01 01:00          1          0.006
      124               01-01 01:00          1          0.005
      125               01-01 01:00          1          0.005

                    Instrument status
years Station code
2017  101                           0
      102                           0
      103                           0
      104                           0
      105                           0
...                               ...
2019  121                           0
      122                           0
      123                           0
      124                           0
      125                           0

[75 rows x 4 columns]

### Question

In the `data_i` DataFrame add in a column displaying the names of the stations.

,Measurement date,Station code,Item code,Average value,Instrument status,Item name
0,2017-01-01 00:00,101,1,0.004,0,SO2
1,2017-01-01 00:00,101,3,0.059,0,NO2
2,2017-01-01 00:00,101,5,1.200,0,CO
3,2017-01-01 00:00,101,6,0.002,0,O3
4,2017-01-01 00:00,101,8,73.000,0,PM10

### Question

In the `data_s` DataFrame drop the columns `Station code` and `Item code`. As these columns have not become redundant. You can find the relevant function in the pandas library [here](https://pandas.pydata.org/docs/reference/index.html).

In [ ]:
data =

,Measurement date,Average value,Instrument status,Item name,Station name(district)
0,2017-01-01 00:00,0.004,0,SO2,Jongno-gu
1,2017-01-01 00:00,0.059,0,NO2,Jongno-gu
2,2017-01-01 00:00,1.200,0,CO,Jongno-gu
3,2017-01-01 00:00,0.002,0,O3,Jongno-gu
4,2017-01-01 00:00,73.000,0,PM10,Jongno-gu

### Question

Given below are the meanings of the values in the `Instrument status`.

- 0: Normal
- 1: Need for calibration
- 2: Abnormal
- 4: Power cut off
- 8: Under repair
- 9: Abnormal data

Using the information given above, add a column in the `data` DataFrame to give the status of the intsruments. Then drop the `Instrument status` column.  

Hint: First create a dictionary from the data, then use the same dictionary to create a DataFrame and then merge the DataFrame. with `data`

In [ ]:
status_dict =

{'Instrument status': [0, 1, 2, 4, 8, 9],
 'Status': ['Normal',
  'Need for calibration',
  'Abnormal',
  'Power cut off',
  'Under repair',
  'Abnormal data']}

In [ ]:
dictdf =

   Instrument status                Status
0                  0                Normal
1                  1  Need for calibration
2                  2              Abnormal
3                  4         Power cut off
4                  8          Under repair
5                  9         Abnormal data

In [ ]:
data =

,Measurement date,Average value,Instrument status,Item name,Station name(district),Status
0,2017-01-01 00:00,0.004,0,SO2,Jongno-gu,Normal
1,2017-01-01 00:00,0.059,0,NO2,Jongno-gu,Normal
2,2017-01-01 00:00,1.200,0,CO,Jongno-gu,Normal
3,2017-01-01 00:00,0.002,0,O3,Jongno-gu,Normal
4,2017-01-01 00:00,73.000,0,PM10,Jongno-gu,Normal

In [ ]:
data =

   Measurement date  Average value Item name Station name(district)  Status
0  2017-01-01 00:00          0.004       SO2              Jongno-gu  Normal
1  2017-01-01 00:00          0.059       NO2              Jongno-gu  Normal
2  2017-01-01 00:00          1.200        CO              Jongno-gu  Normal
3  2017-01-01 00:00          0.002        O3              Jongno-gu  Normal
4  2017-01-01 00:00         73.000      PM10              Jongno-gu  Normal

### Question

Extract the time series data, that is year, month, date and hour form the `Measurement date` column. Once all the data is extrcted drop the `Measurement date` column.

This operation might take some time as the dataset we are working with is very large.

In [ ]:
data['Year'] =
data['Month'] =
data['Date'] =
data['Hour'] =

,Measurement date,Average value,Item name,Station name(district),Status,Year,Month,Date,Hour
0,2017-01-01 00:00,0.004,SO2,Jongno-gu,Normal,2017,1,1,0
1,2017-01-01 00:00,0.059,NO2,Jongno-gu,Normal,2017,1,1,0
2,2017-01-01 00:00,1.200,CO,Jongno-gu,Normal,2017,1,1,0
3,2017-01-01 00:00,0.002,O3,Jongno-gu,Normal,2017,1,1,0
4,2017-01-01 00:00,73.000,PM10,Jongno-gu,Normal,2017,1,1,0

In [ ]:
data =

,Average value,Item name,Station name(district),Status,Year,Month,Date,Hour
0,0.004,SO2,Jongno-gu,Normal,2017,1,1,0
1,0.059,NO2,Jongno-gu,Normal,2017,1,1,0
2,1.200,CO,Jongno-gu,Normal,2017,1,1,0
3,0.002,O3,Jongno-gu,Normal,2017,1,1,0
4,73.000,PM10,Jongno-gu,Normal,2017,1,1,0